name: CI
on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: aarch64-apple-darwin
            arch: linux/arm64/v8
          - target: aarch64-pc-windows-msvc
            arch: linux/arm64/v8
          - target: aarch64-unknown-linux-musl
            arch: linux/arm64/v8
          - target: aarch64-unknown-linux-gnu
            arch: linux/arm64/v8
          - target: arm-unknown-linux-gnueabi
            arch: linux/arm/v7
          - target: arm-unknown-linux-gnueabihf
            arch: linux/arm/v7
          - target: arm-unknown-linux-musleabi
            arch: linux/arm/v7
          - target: arm-unknown-linux-musleabihf
            arch: linux/arm/v7
          - target: armv7-unknown-linux-gnueabi
            arch: linux/arm/v7
          - target: armv7-unknown-linux-musleabi
            arch: linux/arm/v7
          - target: armv7-unknown-linux-musleabihf
            arch: linux/arm/v7
          - target: armv7-unknown-linux-gnueabihf
            arch: linux/arm/v7
          - target: i686-unknown-linux-musl
            arch: linux/386
          - target: i686-pc-windows-gnu
            arch: linux/386
          - target: i686-pc-windows-msvc
            arch: linux/386
          - target: i686-unknown-linux-gnu
            arch: linux/386
          - target: x86_64-apple-darwin
            arch: linux/amd64
          - target: x86_64-pc-windows-gnu
            arch: linux/amd64
          - target: x86_64-pc-windows-msvc
            arch: linux/amd64
          - target: x86_64-unknown-linux-musl
            arch: linux/amd64
          - target: x86_64-unknown-linux-gnu
            arch: linux/amd64
    name: Rust project
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: network=host
      - name: Build with Docker
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: localhost:5000/RedstoneWizard08/temp:latest
          platforms: ${{ matrix.arch }}
      - name: Move the artifact
        id: move
        env:
          TARGET: ${{ matrix.target }}
        run: |
          docker create --name tmp localhost:5000/RedstoneWizard08/temp:latest
          docker cp tmp:/usr/src/packtool/target/release/packtool .
          cp packtool packtool-$(bash getarch.sh)
          echo "::set-output name=executable::packtool-$(bash getarch.sh)"
          docker rm tmp
      - name: Upload the artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.move.outputs.executable }}
          path: ${{ steps.move.outputs.executable }}
