name: CI
on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target:
          - aarch64-apple-darwin
          - aarch64-pc-windows-msvc
          - aarch64-unknown-linux-musl
          - aarch64-unknown-linux-gnu
          - arm-unknown-linux-gnueabi
          - arm-unknown-linux-gnueabihf
          - arm-unknown-linux-musleabi
          - arm-unknown-linux-musleabihf
          - armv7-unknown-linux-gnueabi
          - armv7-unknown-linux-musleabi
          - armv7-unknown-linux-musleabihf
          - armv7-unknown-linux-gnueabihf
          - i686-unknown-linux-musl
          - i686-pc-windows-gnu
          - i686-pc-windows-msvc
          - i686-unknown-linux-gnu
          - x86_64-apple-darwin
          - x86_64-pc-windows-gnu
          - x86_64-pc-windows-msvc
          - x86_64-unknown-linux-musl
          - x86_64-unknown-linux-gnu
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Install the Rust compiler
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
      - name: Setup caching
        uses: Swatinem/rust-cache@v1
      - name: Check the code
        uses: actions-rs/cargo@v1
        with:
          command: check
      - name: Build the binary application
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features --target ${{ matrix.target }}
      - name: Move the artifact
        env:
          TARGET: ${{ matrix.target }}
        run: |
          cp target/${TARGET}/release/packtool packtool-$(bash getarch.sh)
